# name of the software
name: Java client library for Posten signature API
# current version of the software

# url of the download button
downloadUrl: https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22no.digipost.signature%22%20AND%20a%3A%22signature-api-client-java%22
# licence of the software

license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

baseurl: "/signature-api-client-java"

currentVersion: "1.2"
versions: ["1.2", "1.1", "1.0"]

collections:
  v1_0:   
    output: true
    permalink: /v1.0/
  v1_1:   
    output: true
    permalink: /v1.1/
  v1_2:
    output: true
    permalink: /v1.2/

# list of additional links on the right of the top menu
headerLinks:
  - title: Download library
    url: https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22no.digipost.signature%22%20AND%20a%3A%22signature-api-client-java%22
  - title: GitHub
    url: https://github.com/digipost/signature-api-client-java
  - title: Digipost
    url: https://www.digipost.no

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/digipost/signature-api-client-java
  - title: Issues
    url: https://github.com/digipost/signature-api-client-java/issues

# header
header:
  color1: "#e32d22"
  color2:
  trianglify: false

# github buttons
githubButton:
  user: digipost
  repo: signature-api-client-java

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account: digipost_no

# facebook buttons
facebook:
  enabled: false
  profileUrl:

# google analytics
analytics:
  trackingid: UA-77734017-1
  domain: auto

# DON'T MODIFY
highlight: rouge

gems:
  - jekyll-redirect-from

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
